config/routes.rb
Rails.application.routes.draw do
  devise_for :clients, controllers: { registrations: 'registrations' }
  resources :account_transactions, except: [:edit, :update, :destroy]

  get 'home', to: 'home#index'
  post 'home/close-account', to: 'home#close_account'
  post 'home/new-account', to: 'home#new_account'

  get 'statement', to: 'statement#index'
  post 'statement/report', to: 'statement#statement_report'

  root "home#index"
end

app/models/account_transaction.rb
class AccountTransaction < ApplicationRecord
  belongs_to :bank_account
  belongs_to :client

  attr_accessor :password_confirmation

  enum kind: { deposit: 0, withdraw: 1, transfer: 2 }

  validates_presence_of :transaction_value, :kind, :bank_account, :client

  validate :correct_password_confirmation

  def correct_password_confirmation
    unless self.client.valid_password?(password_confirmation)
      errors.add(:password_confirmation, "Invalid password")
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  belongs_to :client
  has_many :account_transactions

  enum status: { active: 0, closed: 1 }
end

app/models/client.rb
class Client < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bank_accounts
end

app/controllers/account_transactions_controller.rb
class AccountTransactionsController < ApplicationController
  before_action :set_account_transaction, only: %i[ show ]
  before_action :set_kinds, only: %i[ new create ]
  before_action :inject_dependencies, only: %i[create]

  # GET /account_transactions
  def index
    @account_transactions = AccountTransaction.where(client_id: current_client.id, bank_account_id: current_client.bank_accounts.active.first.id)
  end

  # GET /account_transactions/1
  def show
  end

  # GET /account_transactions/new
  def new
    @account_transaction = AccountTransaction.new
  end

  # GET /account_transactions/1/edit
  def edit
  end

  # POST /account_transactions
  def create
    @account_transaction = AccountTransaction.new(handle_submit(account_transaction_params))

    if @transaction_service.allow_transaction(@account_transaction)
      if @account_transaction.save
        @transaction_service.update_account_balance(@account_transaction)

        redirect_to @account_transaction, notice: "Account transaction was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
    else
      redirect_to new_account_transaction_path, notice: "High value transaction, check your balance!"
    end
  end

  private
    def set_account_transaction
      @account_transaction = AccountTransaction.find(params[:id])
    end

    def set_kinds
      @kinds = AccountTransaction.kinds.keys
    end

    def inject_dependencies
      @transaction_service = TransactionService.new
    end

    def handle_submit(account_transaction_params)
      bank_account = BankAccount.where(client_id: current_client.id, status: :active).first
      account_transaction_params["transaction_value"]&.delete!('.')
      account_transaction_params = account_transaction_params.merge(
        {
          "bank_account_id" =>  bank_account.id,
          "client_id" => current_client.id
        }
      )
    end

    # Only allow a list of trusted parameters through.
    def account_transaction_params
      params.require(:account_transaction).permit(:transaction_value, :kind, :destination_bank_account, :password_confirmation)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_client!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @account = BankAccount.where(client_id: current_client.id, status: :active).first
  end

  def close_account
    account = BankAccount.find(params[:account_id])
    account.status = :closed

    redirect_to home_path, notice: 'Account was successfully closed' if account.save
  end
  
  def new_account
    account_registration = AccountRegistrationService.new(current_client).create_bank_account

    redirect_to home_path, notice: 'Account was successfully opened' if account_registration
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    super do |client|
      AccountRegistrationService.new(client).create_bank_account
    end
  end
end

app/controllers/statement_controller.rb
class StatementController < ApplicationController
  def index
  end

  def statement_report
    start_date = Date.parse(params[:start_date]).beginning_of_day
    end_date = Date.parse(params[:end_date]).end_of_day
      
    @bank_account = BankAccount.where(client_id: current_client.id, status: :active).first
    @statement_report = AccountTransaction.where("created_at >= ? AND created_at <= ? AND client_id = ?", start_date, end_date, current_client.id)
    
    render 'statement/statement_report'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bank_account_helper.rb
module BankAccountHelper
  def cent_to_real(cents)
    number_with_precision(cents/100.0, precision: 2, separator: ',', delimiter: '.')
  end
end

app/views/account_transactions/_account_transaction.html.erb
<div id="<%= dom_id account_transaction %>">
  <td>
    R$ <%= cent_to_real(account_transaction.transaction_value) %>
  </td>

  <td>
    <%= account_transaction.kind %>
  </td>

  <td>
    <%= account_transaction.bank_account.account_number %>
  </td>

  <td>
    <%= account_transaction.destination_bank_account %>
  </td>

  <td>
    <%= account_transaction.created_at.strftime("%d/%m/%Y %H:%M") %>
  </td>

</div>

app/views/account_transactions/_form.html.erb
<%= form_with(model: account_transaction, class: "w-75") do |form| %>
  <% if account_transaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(account_transaction.errors.count, "error") %> prohibited this account_transaction from being saved:</h2>

      <ul>
        <% account_transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :transaction_value, class: "form-label" %>
    <%= form.text_field :transaction_value, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :kind, class: "form-label" %>
    <%= form.collection_select :kind, @kinds, :to_s, :to_s,  {}, { class: 'form-select'} %>
  </div>

  <div class="mb-3">
    <%= form.label :destination_bank_account, class: "form-label" %>
    <p>Inform when the transaction is of the transfer kind</p>
    <%= form.text_field :destination_bank_account, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :password_confirmation, class: "form-label" %>
    <%= form.password_field :password_confirmation, class: "form-control" %>
  </div>

  <div>
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/account_transactions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Account transactions</h1>

<div id="account_transactions">
<table class="table">
  <thead>
    <tr>
      <th scope="col">Transaction Value</th>
      <th scope="col">kind</th>
      <th scope="col">Bank Account</th>
      <th scope="col">Destination Account</th>
      <th scope="col">Created At</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @account_transactions.each do |account_transaction| %>
        <tr>
    <%= render account_transaction %>
        <td>
      <%= link_to "Show", account_transaction %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<%= link_to "New account transaction", new_account_transaction_path %>

app/views/account_transactions/new.html.erb
<p style="color: red"><%= notice %></p>

<h1>New account transaction</h1>

<%= render "form", account_transaction: @account_transaction %>

<br>

<div>
  <%= link_to "Back to account transactions", account_transactions_path %>
</div>

app/views/account_transactions/show.html.erb
<p style="color: green"><%= notice %></p>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Transaction Value</th>
      <th scope="col">kind</th>
      <th scope="col">Bank Account</th>
      <th scope="col">Destination</th>
      <th scope="col">Created At</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <%= render @account_transaction %>
    </tr>
  </tbody>
</table>

<div>
  <%= link_to "Back to account transactions", account_transactions_path %>
</div>

app/views/home/index.html.erb
<div class="card w-50">
  <div class="card-header row">
    <div class="col align-self-center">
      Account      
    </div>
    <% if @account %>
      <div class="col p-2">
        <%= button_to home_close_account_path(account_id: @account.id), class: "btn btn-primary" do %>
          Close Account
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="card-body">
    <h5 class="card-title">R$ <%= @account ? cent_to_real(@account.account_balance) : 0 %></h5>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrokenBank</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= stylesheet_link_tag 'styles' %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

    <div class="d-flex flex-row mb-3">
      <div class="p-2">
        <%= button_to destroy_client_session_path, class: "btn btn-primary no-print" , method: :delete do %>
          Logout
        <% end %>
      </div>

      <div class="p-2">
        <%= link_to edit_client_registration_path, class: "btn btn-primary no-print" do %>
          Edit Client
        <% end %> 
      </div>

      <div class="p-2">
        <%= link_to home_path, class: "btn btn-primary no-print" do %>
          Home
        <% end %> 
      </div>

      <% unless current_client.bank_accounts.active.first %>
        <div class="p-2">
          <%= button_to home_new_account_path, class: "btn btn-primary no-print" do %>
            New Account
          <% end %> 
        </div>
      <% end %>

      <div class="p-2">
        <%= link_to account_transactions_path, class: "btn btn-primary no-print" do %>
          Transactions
        <% end %> 
      </div>

      <div class="p-2">
        <%= link_to statement_path, class: "btn btn-primary no-print" do %>
          Statements
        <% end %> 
      </div>
    </div>

    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "devise" %>
    <%= javascript_include_tag "devise" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/statement/index.html.erb
<%= form_with(url: statement_report_path, method: :post) do |form| %>
  <div class="card mx-auto mt-5" style="width: 400px;">
    <div class="card-body">
      <div class="row">
        <div class="col">
          <%= form.label :start_date, "Data Inicial" %>
          <%= form.date_field :start_date, class: "form-control" %>
        </div>
        <div class="col">
          <%= form.label :end_date, "Data Final" %>
          <%= form.date_field :end_date, class: "form-control" %>
        </div>
      </div>
      <div class="row mt-3">
        <div class="col text-center">
          <%= form.submit "Enviar", class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/statement/statement_report.html.erb
<div class="card">
  <div class="card-header">
    <h3>Extrato Bancário</h3>
  </div>
  <div class="card-body">
    <table class="table">
      <thead>
        <tr>
          <th>Data e Hora</th>
          <th>Descrição da Transação</th>
          <th>Valor da Transação</th>
        </tr>
      </thead>
      <tbody>
        <% @statement_report.each do |report| %>
          <tr>
            <td><%= report.created_at.strftime("%d/%m/%Y %H:%M") %></td>
            <td><%= report.kind %></td>
            <td>R$ <%= cent_to_real(report.transaction_value) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="row">
      <div class="col-6">
        <p>Saldo Atual: R$ <%= cent_to_real(@bank_account.account_balance) %></p>
        <p>Número da Conta Bancária:  <%= @bank_account.account_number %></p>
      </div>
    </div>
  </div>
  <div class="card-footer text-end">
    <button class="btn btn-primary no-print" onclick="window.print()">Imprimir</button>
  </div>
</div>